dist: trusty
sudo: false
language: java
script:
  - gradle check
  - echo org.kleini.bricklink.login=$BRICKLINK_LOGIN >bricklink/src/main/resources/myconfiguration.properties
  - echo org.kleini.bricklink.password=$BRICKLINK_PASSWORD >>bricklink/src/main/resources/myconfiguration.properties
  - gradle bricklink:determineSetValues -PappArgs=setValues.csv
jdk:
  - openjdk8
