dist: bionic
sudo: false

language: java

env:
  - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

addons:
  chrome: stable
  apt:
    sources:
      - sourceline: 'ppa:cwchien/gradle'
    packages:
      - openjdk-8-jdk-headless
      - gradle
      - lftp

jobs:
  include:
    - script:
        - /usr/bin/gradle check --stacktrace
    - stage: automation
      name: "Determine set values"
      install:
        - wget -N https://chromedriver.storage.googleapis.com/$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip -P /tmp/
        - unzip /tmp/chromedriver_linux64.zip -d "${HOME}/bin/"
        - rm /tmp/chromedriver_linux64.zip
      before_script:
        - google-chrome-stable --version
        - chromedriver --version
        - echo org.kleini.bricklink.login=$BRICKLINK_LOGIN >bricklink/src/main/resources/myconfiguration.properties
        - echo org.kleini.bricklink.password=$BRICKLINK_PASSWORD >>bricklink/src/main/resources/myconfiguration.properties
      script:
        - export DATE=$(date +%Y%m%d)
        - /usr/bin/gradle bricklink:determineSetValues -PappArgs=setValues-${DATE}.txt
        - lftp -e "open sftp://${UPLOAD_LOGIN}:${UPLOAD_PASS}@home19889699.1and1-data.host; put bricklink/setValues-${DATE}.txt; exit"
    - stage: automation
      name: "List available stamps"
      before_script:
        - echo org.kleini.prodws.mandantId=$PRODWS_MANDANTID >bricklink/src/main/resources/myconfiguration.properties
        - echo org.kleini.prodws.login=$PRODWS_LOGIN >>bricklink/src/main/resources/myconfiguration.properties
        - echo org.kleini.prodws.password=$PRODWS_PASSWORD >>bricklink/src/main/resources/myconfiguration.properties
      script:
        - /usr/bin/gradle bricklink:listStamps

