//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.02.17 at 10:55:44 AM CET
//

package org.kleini.brickstore.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * {@link BrickStoreXML} Class for the root element of BrickStore XML files.
 *
 * @author <a href="mailto:himself@kleini.org">Marcus Klein</a>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inventory",
    "guiState"
})
@XmlRootElement()
public class BrickStoreXML {

    @XmlElement(name = "Inventory", required = true)
    protected Inventory inventory;

    @XmlElement(name = "GuiState", required = true)
    protected GuiState guiState;

    public BrickStoreXML() {
        super();
    }

    public Inventory getInventory() {
        return inventory;
    }

    public void setInventory(Inventory inventory) {
        this.inventory = inventory;
    }

    public GuiState getGuiState() {
        return guiState;
    }

    public void setGuiState(GuiState guiState) {
        this.guiState = guiState;
    }
}
