//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.17 at 10:55:44 AM CET 
//

package org.kleini.brickstore.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * {@link ItemView} stores the current view configuration of BrickStore.
 *
 * @author <a href="mailto:himself@kleini.org">Marcus Klein</a>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "columnOrder",
    "columnWidths",
    "columnWidthsHidden",
    "sortColumn",
    "sortDirection"
})
@XmlRootElement(name = "ItemView")
public class ItemView {

    @XmlElement(name = "ColumnOrder", required = true)
    protected String columnOrder;

    @XmlElement(name = "ColumnWidths", required = true)
    protected String columnWidths;

    @XmlElement(name = "ColumnWidthsHidden", required = true)
    protected String columnWidthsHidden;

    @XmlElement(name = "SortColumn", required = true)
    protected int sortColumn;

    @XmlElement(name = "SortDirection", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sortDirection;

    public ItemView() {
        super();
    }

    public String getColumnOrder() {
        return columnOrder;
    }

    public void setColumnOrder(String columnOrder) {
        this.columnOrder = columnOrder;
    }

    public String getColumnWidths() {
        return columnWidths;
    }

    public void setColumnWidths(String columnWidths) {
        this.columnWidths = columnWidths;
    }

    public String getColumnWidthsHidden() {
        return columnWidthsHidden;
    }

    public void setColumnWidthsHidden(String columnWidthsHidden) {
        this.columnWidthsHidden = columnWidthsHidden;
    }

    public int getSortColumn() {
        return sortColumn;
    }

    public void setSortColumn(int sortColumn) {
        this.sortColumn = sortColumn;
    }

    public String getSortDirection() {
        return sortDirection;
    }

    public void setSortDirection(String sortDirection) {
        this.sortDirection = sortDirection;
    }
}
