//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.02.17 at 10:55:44 AM CET
//

package org.kleini.brickstore.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * {@link ItemView} stores the current view configuration of BrickStore.
 *
 * Some examples:
 * <ItemView>
 *   <ColumnOrder>0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30</ColumnOrder>
 *   <ColumnWidths>21,45,65,173,35,95,35,53,53,35,35,53,433,199,77,35,53,35,53,35,53,0,0,0,0,0,0,35,35,53,53</ColumnWidths>
 *   <ColumnWidthsHidden>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,53,53,53,53,65,35,35,35,53,53</ColumnWidthsHidden>
 *   <SortColumn>0</SortColumn>
 *   <SortDirection>A</SortDirection>
 * </ItemView>
 * <ItemView>
 *   <ColumnOrder>0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30</ColumnOrder>
 *   <ColumnWidths>21,45,65,173,35,95,35,53,53,35,35,53,173,199,77,35,53,35,53,35,53,0,0,0,0,0,0,35,35,53,53</ColumnWidths>
 *   <ColumnWidthsHidden>0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,53,53,53,53,65,35,35,35,53,53</ColumnWidthsHidden>
 *   <SortColumn>0</SortColumn>
 *   <SortDirection>A</SortDirection>
 * </ItemView>
 * 0 Include
 * 1 Image
 * 2 Part ID
 * 3 Part Name
 * 4 Condition
 * 5 Color
 * 6 Quantity
 * 7 Price
 * 8 Total price
 * 9 Bulk
 * 10 Ausverkauf
 * Columm 11 is Comments
 * Column 12 is Remarks (200)
 * 13 Category
 * 14 ItemType
 * 15 Tiered pricing count 1
 * 16 Tiered pricing price 1
 * 17 Tiered pricing count 2
 * 18 Tiered pricing price 2
 * 19 Tiered pricing count 3
 * 20 Tiered pricing price 3
 * @author <a href="mailto:himself@kleini.org">Marcus Klein</a>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "columnOrder",
    "columnWidths",
    "columnWidthsHidden",
    "sortColumn",
    "sortDirection"
})
@XmlRootElement(name = "ItemView")
public class ItemView {

    @XmlElement(name = "ColumnOrder", required = true)
    protected String columnOrder;

    @XmlElement(name = "ColumnWidths", required = true)
    protected String columnWidths;

    @XmlElement(name = "ColumnWidthsHidden", required = true)
    protected String columnWidthsHidden;

    @XmlElement(name = "SortColumn", required = true)
    protected int sortColumn;

    @XmlElement(name = "SortDirection", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String sortDirection;

    public ItemView() {
        super();
    }

    public String getColumnOrder() {
        return columnOrder;
    }

    public void setColumnOrder(String columnOrder) {
        this.columnOrder = columnOrder;
    }

    public String getColumnWidths() {
        return columnWidths;
    }

    public void setColumnWidths(String columnWidths) {
        this.columnWidths = columnWidths;
    }

    public String getColumnWidthsHidden() {
        return columnWidthsHidden;
    }

    public void setColumnWidthsHidden(String columnWidthsHidden) {
        this.columnWidthsHidden = columnWidthsHidden;
    }

    public int getSortColumn() {
        return sortColumn;
    }

    public void setSortColumn(int sortColumn) {
        this.sortColumn = sortColumn;
    }

    public String getSortDirection() {
        return sortDirection;
    }

    public void setSortDirection(String sortDirection) {
        this.sortDirection = sortDirection;
    }
}
