//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.17 at 10:55:44 AM CET 
//

package org.kleini.brickstore.data;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * org.kleini.brickstore.data package.
 * <p>An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content. The Java
 * representation of XML content can consist of schema derived interfaces and classes representing the binding of schema type definitions,
 * element declarations and model groups. Factory methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Condition_QNAME = new QName("", "Condition");
    private final static QName _ItemID_QNAME = new QName("", "ItemID");
    private final static QName _CategoryName_QNAME = new QName("", "CategoryName");
    private final static QName _ColorName_QNAME = new QName("", "ColorName");
    private final static QName _ColorID_QNAME = new QName("", "ColorID");
    private final static QName _ColumnOrder_QNAME = new QName("", "ColumnOrder");
    private final static QName _Remarks_QNAME = new QName("", "Remarks");
    private final static QName _ColumnWidthsHidden_QNAME = new QName("", "ColumnWidthsHidden");
    private final static QName _Bulk_QNAME = new QName("", "Bulk");
    private final static QName _ItemTypeName_QNAME = new QName("", "ItemTypeName");
    private final static QName _SortColumn_QNAME = new QName("", "SortColumn");
    private final static QName _OrigQty_QNAME = new QName("", "OrigQty");
    private final static QName _OrigPrice_QNAME = new QName("", "OrigPrice");
    private final static QName _Qty_QNAME = new QName("", "Qty");
    private final static QName _Status_QNAME = new QName("", "Status");
    private final static QName _CategoryID_QNAME = new QName("", "CategoryID");
    private final static QName _Price_QNAME = new QName("", "Price");
    private final static QName _ItemName_QNAME = new QName("", "ItemName");
    private final static QName _SortDirection_QNAME = new QName("", "SortDirection");
    private final static QName _ItemTypeID_QNAME = new QName("", "ItemTypeID");
    private final static QName _ColumnWidths_QNAME = new QName("", "ColumnWidths");
    private final static QName _TotalWeight_QNAME = new QName("", "TotalWeight");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.kleini.brickstore.data
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ItemView }
     */
    public ItemView createItemView() {
        return new ItemView();
    }

    /**
     * Create an instance of {@link Inventory }
     */
    public Inventory createInventory() {
        return new Inventory();
    }

    /**
     * Create an instance of {@link Item }
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link GuiState }
     */
    public GuiState createGuiState() {
        return new GuiState();
    }

//    public BrickStoreXML createBrickStoreXML() {
//        return new BrickStoreXML();
//    }
//
    @XmlElementDecl(namespace = "", name="BrickStoreXML")
    public JAXBElement<BrickStoreXML> createBrickStoreXML(BrickStoreXML brickStoreXML) {
        return new JAXBElement<BrickStoreXML>(new QName("", "BrickStoreXML"), BrickStoreXML.class, brickStoreXML);
    }

    @XmlElementDecl(namespace = "", name="BrickStockXML")
    public JAXBElement<BrickStoreXML> createBrickStockXML(BrickStoreXML brickStoreXML) {
        return new JAXBElement<BrickStoreXML>(new QName("", "BrickStockXML"), BrickStoreXML.class, brickStoreXML);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "Condition")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createCondition(String value) {
        return new JAXBElement<String>(_Condition_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "ItemID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createItemID(String value) {
        return new JAXBElement<String>(_ItemID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "CategoryName")
    public JAXBElement<String> createCategoryName(String value) {
        return new JAXBElement<String>(_CategoryName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "ColorName")
    public JAXBElement<String> createColorName(String value) {
        return new JAXBElement<String>(_ColorName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "ColorID")
    public JAXBElement<Integer> createColorID(Integer value) {
        return new JAXBElement<Integer>(_ColorID_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "ColumnOrder")
    public JAXBElement<String> createColumnOrder(String value) {
        return new JAXBElement<String>(_ColumnOrder_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "Remarks")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createRemarks(String value) {
        return new JAXBElement<String>(_Remarks_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "ColumnWidthsHidden")
    public JAXBElement<String> createColumnWidthsHidden(String value) {
        return new JAXBElement<String>(_ColumnWidthsHidden_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "Bulk")
    public JAXBElement<Integer> createBulk(Integer value) {
        return new JAXBElement<Integer>(_Bulk_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "ItemTypeName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createItemTypeName(String value) {
        return new JAXBElement<String>(_ItemTypeName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SortColumn")
    public JAXBElement<Integer> createSortColumn(Integer value) {
        return new JAXBElement<Integer>(_SortColumn_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "OrigQty")
    public JAXBElement<Integer> createOrigQty(Integer value) {
        return new JAXBElement<Integer>(_OrigQty_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "OrigPrice")
    public JAXBElement<BigDecimal> createOrigPrice(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_OrigPrice_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "Qty")
    public JAXBElement<Integer> createQty(Integer value) {
        return new JAXBElement<Integer>(_Qty_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "Status")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "CategoryID")
    public JAXBElement<Integer> createCategoryID(Integer value) {
        return new JAXBElement<Integer>(_CategoryID_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "Price")
    public JAXBElement<BigDecimal> createPrice(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Price_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "ItemName")
    public JAXBElement<String> createItemName(String value) {
        return new JAXBElement<String>(_ItemName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "SortDirection")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSortDirection(String value) {
        return new JAXBElement<String>(_SortDirection_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "ItemTypeID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createItemTypeID(String value) {
        return new JAXBElement<String>(_ItemTypeID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     */
    @XmlElementDecl(namespace = "", name = "ColumnWidths")
    public JAXBElement<String> createColumnWidths(String value) {
        return new JAXBElement<String>(_ColumnWidths_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "", name = "TotalWeight")
    public JAXBElement<BigDecimal> createTotalWeight(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TotalWeight_QNAME, BigDecimal.class, null, value);
    }
}
