version: 2.1

executors:
  executor:
    docker:
      - image: cimg/openjdk:8.0.282

jobs:
  build:
    executor: executor
    steps:
      - checkout
      - run:
          name: Build
          command: |
            gradle build bricklink:fatJar
            pwd
            ls bricklink/build/libs
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - store_artifacts:
          path: bricklink/build/libs
  setValues:
    executor: executor
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - checkout
      - run:
          name: Determine set value
          command: |
            export DATE=$(date +%Y%m%d)
            echo org.kleini.bricklink.login=$BRICKLINK_LOGIN >bricklink/src/main/resources/myconfiguration.properties
            echo org.kleini.bricklink.password=$BRICKLINK_PASSWORD >>bricklink/src/main/resources/myconfiguration.properties
            gradle bricklink:determineSetValues -PappArgs=setValues-${DATE}.txt
            sudo apt-get update
            sudo apt-get install lftp
            getent hosts home19889699.1and1-data.host
            lftp -e "set sftp:auto-confirm yes; open -u ${UPLOAD_LOGIN} --env-password sftp://home19889699.1and1-data.host; put bricklink/setValues-${DATE}.txt; exit"

orbs:
  browser-tools: circleci/browser-tools@1.1.1

workflows:
  version: 2
  build:
    jobs:
      - build
      - setValues
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
      - setValues
